### ISSUE TITLE
delete_expired_uploads import error

### ISSUE THREAD

**Issue by jdavid** [juliomalegria/django-chunked-upload#12]
Hello,

Import Error:

    $ ... delete_expired_uploads --help
    Traceback (most recent call last):
      ...
      File "/.../django-chunked-upload/chunked_upload/management/commands/delete_expired_uploads.py", line 7, in <module>
        from .settings import EXPIRATION_DELTA
    ImportError: No module named settings

Guess it should be ``from chunked_upload.settings import EXPIRATION_DELTA``

PS: Thanks for this product!

**Comment by jdavid** [comment]
Worse, the query is just the opposite, instead of deleting expired uploads, it deletes non expired uploads:

    -        qs = qs.filter(created_on__gte=(timezone.now() - EXPIRATION_DELTA))
    +        qs = qs.filter(created_on__lt=(timezone.now() - EXPIRATION_DELTA))

**Comment by juliomalegria** [comment]
You're totally right about those two things! I'm so sorry. I'm going to fix them right away and make a new build.

**Comment by juliomalegria** [comment]
Fixed here: d99f9d7.
New version ([`1.0.4`](https://pypi.python.org/pypi/django-chunked-upload/1.0.4)) in PyPI.

Thanks @jdavid for pointing this out!
