### ISSUE TITLE
Change offset field type in ChunkedUpload model to BigIntegerField

### ISSUE THREAD

**Issue by hackdna** [juliomalegria/django-chunked-upload#14]
Offset is a PositiveIntegerField with a max value of 2147483647 when PostgreSQL is used (https://code.djangoproject.com/ticket/12030#comment:14). This prevents uploads of files that are size of 2GB and larger.

**Comment by juliomalegria** [comment]
You're right @hackdna. That field should be a BigIntegerField.

**Comment by hackdna** [comment]
Thank you very much for a quick fix. Any idea when will this change make it to PyPI?

**Comment by juliomalegria** [comment]
I was kinda waiting for a bigger change for the next release, but I guess I could push it to PyPI.
I'll try to do it today.

**Comment by hackdna** [comment]
That would be great. We have a use case for uploading large files.

**Comment by juliomalegria** [comment]
[Version](https://pypi.python.org/pypi/django-chunked-upload/1.0.5) 1.0.5 in PyPI :)

**Comment by hackdna** [comment]
Installed and tested it - works fine, thank you!

**Comment by juliomalegria** [comment]
:+1:
